version: 0.2

phases:
  install:
    commands:
      - echo CODEBUILD_SRC_DIR - $CODEBUILD_SRC_DIR
      - echo GOPATH - $GOPATH
      - echo GOROOT - $GOROOT
  build:
    commands:
      - echo Build started...
      - echo Getting packages
      - go get ./...
      - echo Building Go application...
      - go build -o application application.go
  post_build:
    commands:
      - echo Build completed.
artifacts:
  files:
    - application
    - go.mod